### ISSUE TITLE
Remove extra info email input box?

### ISSUE THREAD

**Issue by aripollak** [adunkman/dc311rn.com#26]
Thanks for this site! I just used it successfully to look up a request I initiated over 311 by phone. 

When trying to use the extra-info-with-email button on Firefox for Android, it redirects correctly to the 311 site, but that site didn't use the info in the query string to look anything up so I still have to type the request number and email again.

**Comment by adunkman** [comment]
Thanks for the report — glad to hear it was useful for you! Looks like there’s something up in the template, when I try this myself the service request number is missing from the URL:

![image](https://user-images.githubusercontent.com/14930/41863380-8a7b27d8-7874-11e8-8880-fff6881467fb.png)

**Comment by adunkman** [comment]
I believe this is fixed and deployed now — @aripollak care to double-check, if you get the chance? Thanks!

**Comment by aripollak** [comment]
Oh cool. Confirmed fixed now!

**Comment by adunkman** [comment]
![gif of person in inflatable pikachu costume dancing](https://media.giphy.com/media/26uf0lQ5P92yiXsas/giphy.gif)
